#pragma once

enum HomieEvent : uint8_t {
  HOMIE_STANDALONE_MODE = 1,
  HOMIE_CONFIGURATION_MODE,
  HOMIE_NORMAL_MODE,
  HOMIE_OTA_STARTED,
  HOMIE_OTA_SUCCESSFUL,
  HOMIE_OTA_FAILED,
  HOMIE_ABOUT_TO_RESET,
  HOMIE_WIFI_CONNECTED,
  HOMIE_WIFI_DISCONNECTED,
  HOMIE_MQTT_CONNECTED,
  HOMIE_MQTT_DISCONNECTED
};
