#ifndef HomieEvent_h
#define HomieEvent_h

enum HomieEvent : unsigned char {
    HOMIE_CONFIGURATION_MODE = 1,
    HOMIE_NORMAL_MODE,
    HOMIE_OTA_MODE,
    HOMIE_ABOUT_TO_RESET,
    HOMIE_WIFI_CONNECTED,
    HOMIE_WIFI_DISCONNECTED,
    HOMIE_MQTT_CONNECTED,
    HOMIE_MQTT_DISCONNECTED
};

#endif
